# Generated by Django 3.2.23 on 2024-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-17', max_length=20, verbose_name='出生日期'),
        ),
    ]
